export interface User {
  id: number,
  name: string,
  username: string,
  gender: string,
  age: number,
  country: string,
  city: string,
  marriage: string,
  children: string,
  avatar: string
}

export const users: User[] = [
  {
    id: 1,
    name: 'Madina',
    username: 'Graham',
    gender: 'female',
    age: 22,
    country: 'Russia',
    city: 'Moskow',
    marriage: 'true',
    children: 'false',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },
  {
    id: 2,
    name: 'Anna',
    username: 'Leanne',
    gender: 'female',
    age: 33,
    country: 'Russia',
    city: 'Piter',
    marriage: 'true',
    children: 'false',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },
  {
    id: 3,
    name: 'Fatima',
    username: 'Lop',
    gender: 'female',
    age: 44,
    country: 'Saudia',
    city: 'Mekka',
    marriage: 'false',
    children: 'false',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },
  {
    id: 4,
    name: 'Lola',
    username: 'Fich',
    gender: 'female',
    age: 32,
    country: 'Saudia',
    city: 'Medina',
    marriage: 'false',
    children: 'false',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },
  {
    id: 5,
    name: 'Maria',
    username: 'Con',
    gender: 'female',
    age: 23,
    country: 'Egypt',
    city: 'Kair',
    marriage: 'true',
    children: 'true',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },
  {
    id: 6,
    name: 'Lila',
    username: 'Graham',
    gender: 'female',
    age: 33,
    country: 'Egypt',
    city: 'Alexandria',
    marriage: 'false',
    children: 'false',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },
  {
    id: 7,
    name: 'Aisha',
    username: 'Leanne',
    gender: 'female',
    age: 22,
    country: 'Russia',
    city: 'Ufa',
    marriage: 'false',
    children: 'false',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },
  {
    id: 8,
    name: 'Eva',
    username: 'Lop',
    gender: 'female',
    age: 55,
    country: 'Egypt',
    city: 'Sheih',
    marriage: 'false',
    children: 'false',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },
  {
    id: 9,
    name: 'Nuna',
    username: 'Fich',
    gender: 'female',
    age: 53,
    country: 'Saudia',
    city: 'Toif',
    marriage: 'false',
    children: 'false',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },
  {
    id: 10,
    name: 'Paba',
    username: 'Con',
    gender: 'female',
    age: 23,
    country: 'Russia',
    city: 'Omsk',
    marriage: 'true',
    children: 'false',
    avatar: 'https://st3.depositphotos.com/14846838/19463/v/1600/depositphotos_194639408-stock-illustration-flat-icon-woman-hijab.jpg'
  },{
    id: 11,
    name: 'Muhammad',
    username: 'Lop',
    gender: 'man',
    age: 20,
    country: 'Egypt',
    city: 'Sheih',
    marriage: 'false',
    children: 'true',
    avatar: 'https://forum-translational-medicine.org/files/Bio-M/ftm/Ungerer.jpg'
  },
  {
    id: 12,
    name: 'Ahmad',
    username: 'Fich',
    gender: 'man',
    age: 54,
    country: 'Saudia',
    city: 'Toif',
    marriage: 'false',
    children: 'false',
    avatar: 'https://forum-translational-medicine.org/files/Bio-M/ftm/Ungerer.jpg'
  },
  {
    id: 13,
    name: 'Mahmud',
    username: 'Con',
    gender: 'man',
    age: 44,
    country: 'Russia',
    city: 'Omsk',
    marriage: 'true',
    children: 'false',
    avatar: 'https://forum-translational-medicine.org/files/Bio-M/ftm/Ungerer.jpg'
  },
]
